### ISSUE TITLE
Refact Yield simulator

### ISSUE THREAD

**Issue by schwepps** [Carbonable/carbonable-home#30]
**Description**
---
Refact yield simulator with latest design

**What code could be improved?**
---
- Design of the yield simulator
- Add scenario selection
- Add KPIs
- Use Fetcher and dedicated routes to save analytics

**Acceptance Criteria**
---

- [x] Yield simulator is responsive
- [x] User can select his preferred scenario (worst, base, best)
- [x] Analytics are saved in database
- [x] Yield simulator is tested at: https://carbonable-dapp.fly.dev/

**Additional context**
---
n/a

**Screenshots**
n/a
