### ISSUE TITLE
Refact offset simulator

### ISSUE THREAD

**Issue by schwepps** [Carbonable/carbonable-home#31]
**Description**
---
Refact offset simulator with latest design

**What code could be improved?**
---
- Design of the offset simulator
- Add scenario selection
- Add KPIs
- Use Fetcher and dedicated routes to save analytics

**Acceptance Criteria**
---

- [x] Offset simulator is responsive
- [x] User can select his preferred scenario (worst, base, best)
- [x] Analytics are saved in database

**Additional context**
---
n/a

**Screenshots**
n/a
