### ISSUE TITLE
[Homepage] - Refact manifesto

### ISSUE THREAD

**Issue by schwepps** [Carbonable/carbonable-home#33]
**Description**
---
Refact manifesto section with animation

**Acceptance Criteria**
---

- [x] New design and animation are respected
- [x] Design is responsive
- [ ] Tested at: https://carbonable-dapp.fly.dev/

**Additional context**
---
(https://www.figma.com/file/23Xxeg0nagkmBodO0dlFfs/Carbonable---Design?node-id=0%3A1)

**Comment by schwepps** [comment]
Design and animation have been changed to be responsive and allow all the animation at the same time.
To be validated with @G2CARBZ
