### ISSUE TITLE
Remove dApp feature from home repo

### ISSUE THREAD

**Issue by schwepps** [Carbonable/carbonable-home#39]
**Acceptance Criteria**
---
- [x] Remove unnecessary pages and components 
- [x] Remove starknet React component
- [ ] Test at https://dev-carbonable-home.fly.dev/
